# Akif Ahmed (AA) and Renee Wang (AC)
# CSE 163 (A)
# Creates word clouds for each text file generated by each
# line in data, so each personality has a word cloud.

import os
from os import path
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from write_to_txt import get_ptypes


def word_cloud(ptype):
    txt_file = str(ptype) + "_word_list.txt"
    pic_file = str(ptype) + "_word_cloud.png"
    t = path.dirname(__file__) if "__file__" in locals() else os.getcwd()
    text = open(path.join(t, txt_file)).read()
    wordcloud = WordCloud(background_color="white").generate(text)
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis("off")
    plt.savefig(pic_file)


def main():
    types = get_ptypes()
    for t in types:
        word_cloud(t)


if __name__ == "__main__":
    main()
